In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[2,8,4],[3,4,5]])

In [3]:
A

array([[1, 2, 3],
       [2, 8, 4],
       [3, 4, 5]])

In [5]:
np.transpose(A)

array([[1, 2, 3],
       [2, 8, 4],
       [3, 4, 5]])

In [6]:
B = np.matrix ('1,2,3;4,5,6;7,8,9')

In [7]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
np.transpose(B)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [9]:
C = np.matrix('1,2,3;4,5,6')

In [10]:
C

matrix([[1, 2, 3],
        [4, 5, 6]])

In [11]:
C.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])