In [1]:
import numpy as np

In [2]:
#Matriz Linha
L = np.array([3,4,5])


In [3]:
L

array([3, 4, 5])

In [4]:
L1 = np.array([[3, 4, 5]])

In [5]:
L1

array([[3, 4, 5]])

In [6]:
L.shape

(3,)

In [7]:
L1.shape

(1, 3)

In [8]:
#Matriz Coluna
C1 = np.array([[3], [4], [5]])

In [9]:
C1

array([[3],
       [4],
       [5]])

In [10]:
C1.shape

(3, 1)

In [11]:
#Matriz Nula
N = np.zeros([2,3])

In [ ]:
N

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
N2 = np.zeros([6,6])

In [13]:
N2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
#Matriz Diagonal
D = np.diag([1,2,3,4,5])

In [15]:
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [16]:
D.shape

(5, 5)

In [17]:
#Matriz Identidade
I = np.eye(7)

In [18]:
I

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## Testando a construção de matrizes utilizando o matrix

In [19]:
#Matriz Linha
L2 = np.matrix('1,2,3')

In [20]:
L2

matrix([[1, 2, 3]])

In [21]:
#Matriz Coluna
C3 = np.matrix('1;2;3')

In [ ]:
C3

matrix([[1],
        [2],
        [3]])

In [ ]:
L2.shape

(1, 3)

In [ ]:
C3.shape

(3, 1)