# Multiplicações de matrizes e matrizes identidades

In [3]:
import numpy as np

### Criando matriz A de ordem 3x3

In [4]:
A = np.matrix('3.0, 7.0, 2.0 ; 9.0, 2.0, 4.0; 8.0, 9.0, 7.0')
print(A)

[[3. 7. 2.]
 [9. 2. 4.]
 [8. 9. 7.]]


### Criando matriz identidade B de ordem 3

In [5]:
B = np.identity(3)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Multiplicação da Matriz identidade B pela Matriz A

### Toda matriz multiplicada por uma matriz identidade DE MESMA ORDEM é ela mesma

### Para A.In = A = In.A, ambas as matrizes devem ter mesma ordem

In [6]:
C = A.dot(B)
print(C)

[[3. 7. 2.]
 [9. 2. 4.]
 [8. 9. 7.]]


In [7]:
D = B.dot(A)
print(D)

[[3. 7. 2.]
 [9. 2. 4.]
 [8. 9. 7.]]


In [ ]:
X = np.matrix('2.0, 4.0; 4.0, 3.0; 3.0, 9.0')
print(X)

In [9]:
E = B.dot(X)
print(E)
E = X.dot(B)
print(E)

[[2. 4.]
 [4. 3.]
 [3. 9.]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)