# Resolução de sistema linear tranformando-o em uma matriz identidade

In [1]:
import numpy as np

## Define a matriz a e printa

In [84]:
A = np.matrix('1.0, 1.0, 2.0 ,9.0; 2.0, 4.0, -3.0, 1.0; 3.0, 6.0, -5.0, 0.0')

A

matrix([[ 1.,  1.,  2.,  9.],
        [ 2.,  4., -3.,  1.],
        [ 3.,  6., -5.,  0.]])

In [85]:
A[1,:] = -2*A[0,:] + A[1,:]

A

matrix([[  1.,   1.,   2.,   9.],
        [  0.,   2.,  -7., -17.],
        [  3.,   6.,  -5.,   0.]])

In [86]:
A[2, :] = A[2, :] - 3*A[0, :]

A

matrix([[  1.,   1.,   2.,   9.],
        [  0.,   2.,  -7., -17.],
        [  0.,   3., -11., -27.]])

In [87]:
A[1, :] = (1/2) * A[1, :]

A

matrix([[  1. ,   1. ,   2. ,   9. ],
        [  0. ,   1. ,  -3.5,  -8.5],
        [  0. ,   3. , -11. , -27. ]])

In [88]:
A[2, :] = A[2, :] - 3*A[1, :]

A

matrix([[ 1. ,  1. ,  2. ,  9. ],
        [ 0. ,  1. , -3.5, -8.5],
        [ 0. ,  0. , -0.5, -1.5]])

In [89]:
A[2, :] = -2*A[2, :]

A

matrix([[ 1. ,  1. ,  2. ,  9. ],
        [ 0. ,  1. , -3.5, -8.5],
        [ 0. ,  0. ,  1. ,  3. ]])

In [91]:
A[0, :] = A[0, :] - 3*A[2, :]

A

matrix([[ 1. ,  1. , -1. ,  0. ],
        [ 0. ,  1. , -3.5, -8.5],
        [ 0. ,  0. ,  1. ,  3. ]])