In [1]:
import numpy as np

In [2]:
A = np.matrix('0.005, 2,4;3, 3.14,7;5,3,9')
print(A)

[[5.00e-03 2.00e+00 4.00e+00]
 [3.00e+00 3.14e+00 7.00e+00]
 [5.00e+00 3.00e+00 9.00e+00]]


In [3]:
Det_A = np.linalg.det(A)

In [4]:
Det_A

-10.763700000000004

In [5]:
from numpy.linalg import det

In [6]:
det(A)

-10.763700000000004