In [1]:
import numpy as np

In [2]:
A = np.matrix('3,2,5, 4;12, 5,3,11; 1,3,5, 8')

In [6]:
A 

matrix([[ 3,  2,  5,  4],
        [12,  5,  3, 11],
        [ 1,  3,  5,  8]])

In [7]:
A1 = A.copy()

In [4]:
A1

NameError: ignored

In [8]:
#troca de linhas
A1[0,0]=1
A1[0,1]= 3
A1[0,2] = 5
A1[0,3]= 8
A1[2,0] = 3
A1[2,1]= 2
A1[2,2]=5
A1[2,3] = 4


In [9]:
A1

matrix([[ 1,  3,  5,  8],
        [12,  5,  3, 11],
        [ 3,  2,  5,  4]])

In [10]:
A2 = A1.copy()

In [11]:
A2

matrix([[ 1,  3,  5,  8],
        [12,  5,  3, 11],
        [ 3,  2,  5,  4]])

In [12]:
A2[1,:] = A2[1,:] - 12*A2[0,:]
print(A2)

[[  1   3   5   8]
 [  0 -31 -57 -85]
 [  3   2   5   4]]


In [13]:
A2[2,:] = A2[2,:] - 3*A2[0,:]
print(A2)

[[  1   3   5   8]
 [  0 -31 -57 -85]
 [  0  -7 -10 -20]]


In [14]:
A3 = A2.copy()

In [15]:
A3[2,:] = -31*A3[2,:] + 7*A2[1,:]
print(A3)

[[  1   3   5   8]
 [  0 -31 -57 -85]
 [  0   0 -89  25]]


In [16]:
A4 = A3.copy()

In [17]:
A4[1,:] = -1/31*A4[1,:]
print (A4)

[[  1   3   5   8]
 [  0   1   1   2]
 [  0   0 -89  25]]


In [18]:
A4[2,:] = -(1/89)*A4[2,:]

In [ ]:
print(A4)

[[1 3 5 8]
 [0 1 1 2]
 [0 0 1 0]]


In [19]:
A5 = A4.copy()

In [20]:
A5[1,:] = -1*A5[2,:] + A5[1,:]

In [21]:
print(A5)

[[1 3 5 8]
 [0 1 0 2]
 [0 0 1 0]]


In [22]:
A5[0,:] = -3*A5[1,:] + A5[0,:]

In [23]:
print(A5)

[[1 0 5 2]
 [0 1 0 2]
 [0 0 1 0]]


In [ ]:
A5[0,:] = -5*A5[2,:] + A5[0,:]

In [24]:
print (A5)

[[1 0 5 2]
 [0 1 0 2]
 [0 0 1 0]]
