In [1]:
#Para essa atividade usar o array ao invés da matrix
import numpy as np
from numpy.linalg import det, inv

In [2]:
np.array?

In [3]:
A = np.array ([[1,2,3], [4,5,6], [7,8,9]])

In [4]:
B = np.array ([[14,7,75], [28,4,88], [10,6,19]])

In [5]:
C = np.array([[3,7,9],[2,1,4],[-2,4,-5]])

In [ ]:
#Matriz Inversa
det(A)

0.0

In [ ]:
det(B)

5707.999999999991

In [ ]:
det(C)

40.99999999999997

In [9]:
Inv_B = inv(B)

In [7]:
Inv_C = inv(C)

In [8]:
Inv_B

array([[-0.07918711,  0.05553609,  0.0553609 ],
       [ 0.06096706, -0.08479327,  0.15206727],
       [ 0.02242467, -0.0024527 , -0.02452698]])

In [ ]:
Inv_C

array([[-0.51219512,  1.73170732,  0.46341463],
       [ 0.04878049,  0.07317073,  0.14634146],
       [ 0.24390244, -0.63414634, -0.26829268]])

In [ ]:
D = B.dot(Inv_B)

In [ ]:
D

array([[ 1.00000000e+00, -5.63785130e-18,  6.59194921e-17],
       [-1.11022302e-16,  1.00000000e+00,  8.32667268e-17],
       [-1.38777878e-17, -2.99239800e-17,  1.00000000e+00]])

In [ ]:
E = C.dot(Inv_C)

In [ ]:
E

array([[ 1.00000000e+00, -4.44089210e-16,  2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  4.44089210e-16,  1.00000000e+00]])

## Propriedades das Matrizes Inversas

In [ ]:
# caso possua inversa A então existe a inversa da inversa.
inv(Inv_B)

array([[14.,  7., 75.],
       [28.,  4., 88.],
       [10.,  6., 19.]])

In [ ]:
B.dot(C)

array([[ -94,  405, -221],
       [ -84,  552, -172],
       [   4,  152,   19]])

In [ ]:
inv(Inv_C)

array([[ 3.,  7.,  9.],
       [ 2.,  1.,  4.],
       [-2.,  4., -5.]])

In [ ]:
#Caso A e B possuirem inversas, então AB também possui inversa (A.B)^-1 = (B)^-1 * (A)^-1
np.matrix?

In [ ]:
np.matrix_equal?

Object `np.matrix_equal` not found.


In [ ]:
np.array_equal(inv(B.dot(C)), inv(C).dot(inv(B)))

False

In [ ]:
inv(B.dot(C))

array([[ 0.15652828, -0.17641906,  0.22361427],
       [ 0.00387988, -0.00385424,  0.01023809],
       [-0.06399234,  0.06797477, -0.07634984]])

In [ ]:
inv(C).dot(inv(B))

array([[ 0.15652828, -0.17641906,  0.22361427],
       [ 0.00387988, -0.00385424,  0.01023809],
       [-0.06399234,  0.06797477, -0.07634984]])

In [ ]:
#o comando np.array_equal remete a termos exatamente iguais, que não é o caso
#pois temos erros envolvendo o arredondamento

In [ ]:
#A inversa de A.T é igual inversa (A).T

In [ ]:
inv(B.T)

array([[-0.07918711,  0.06096706,  0.02242467],
       [ 0.05553609, -0.08479327, -0.0024527 ],
       [ 0.0553609 ,  0.15206727, -0.02452698]])

In [ ]:
Inv_B.T

array([[-0.07918711,  0.06096706,  0.02242467],
       [ 0.05553609, -0.08479327, -0.0024527 ],
       [ 0.0553609 ,  0.15206727, -0.02452698]])