In [ ]:
  import numpy as np

In [ ]:
A = np.matrix('1,2,3;4,5,6;7,8,9')
B = np.matrix('4,5,8;7,4,8')
C = np.matrix('9,8,7;6,5,4;3,2,1')
print(A)
print(B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 8]
 [7 4 8]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Soma 
S = A+B
print(S)

ValueError: ignored

In [ ]:
#soma de linhas

In [ ]:
L = A[0,0] + B[0,0]

In [ ]:
L

5

In [ ]:
L1 = A[0,:] + B[0,:]
print(L1)

[[ 5  7 11]]


In [ ]:
L2 = A[2,:] + B[1,:]
print(L2)

[[14 12 17]]


In [ ]:
S = A + C
print(S)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
Sub = A - C
print(Sub)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
#Multiplicação de Matrizes
m = A*C
print(m)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#multiplicação por um escalar
k = 2
print(k*B)

[[ 8 10 16]
 [14  8 16]]


In [ ]:
#Divisão de Matrizes
D1 = A/C

In [ ]:
D1

matrix([[0.11111111, 0.25      , 0.42857143],
        [0.66666667, 1.        , 1.5       ],
        [2.33333333, 4.        , 9.        ]])

In [ ]:
#Multiplicação Matricial
F = C.dot(A)

In [ ]:
F

matrix([[ 90, 114, 138],
        [ 54,  69,  84],
        [ 18,  24,  30]])

In [ ]:
F1 = A.dot(C)
print(F1)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
F12 = A[0,:].dot(C[:,1])
print(F12)

[[24]]
