In [ ]:
 import numpy as np
from numpy.linalg import inv, det

In [ ]:
A = np.matrix('-1,2;2,1')
B= np.matrix('-1;5')

In [ ]:
A

matrix([[-1,  2],
        [ 2,  1]])

In [ ]:
B

matrix([[-1],
        [ 5]])

In [ ]:
D = det(A)

In [ ]:
D

-5.000000000000001

In [ ]:
Ax = A.copy()
Ax[:,0] = B[:,0]
Ax

matrix([[-1,  2],
        [ 5,  1]])

In [ ]:
Ay = A.copy()
Ay[:,1] = B[:,0]
Ay

matrix([[-1, -1],
        [ 2,  5]])

In [ ]:
Dx = det(Ax)
Dx

-11.000000000000002

In [ ]:
Dy = det(Ay)
Dy

-2.9999999999999996

In [ ]:
#Solução
x = Dx/D
x
y = Dy/D
y

0.5999999999999998

In [ ]:
x

2.2

In [ ]:
y

0.5999999999999998

##Cramer 3x3

In [ ]:
G = np.matrix('1,2,3;6,0,1;4,5,-1')
H = np.matrix('3;-6;1')

In [ ]:
D3 = det(G)
D3

104.99999999999997

In [ ]:
Gx = G.copy()
Gx[:,0] = H[:,0]
Gx

matrix([[ 3,  2,  3],
        [-6,  0,  1],
        [ 1,  5, -1]])

In [ ]:
Gy = G.copy()
Gy[:,1] = H[:,0]
Gy

matrix([[ 1,  3,  3],
        [ 6, -6,  1],
        [ 4,  1, -1]])

In [ ]:
Gz = G.copy()
Gz[:,2] = H[:,0]
Gz

matrix([[ 1,  2,  3],
        [ 6,  0, -6],
        [ 4,  5,  1]])

In [ ]:
Det4 = det(Gx)
Det4

-114.99999999999991

In [ ]:
Det5 = det(Gy)
Det5

124.99999999999994

In [ ]:
Det6 = det(Gz)
Det6

59.999999999999986

In [ ]:
x = Det4/D3
x

-1.0952380952380947

In [ ]:
y = Det5/D3
y

1.1904761904761902

In [ ]:
z = Det6/D3
z

0.5714285714285714