In [1]:
import numpy as np

In [3]:
A = np.array([[2,1], [2,3]])

In [4]:
A

array([[2, 1],
       [2, 3]])

In [5]:
B = np.array([[1,2,3],[4,5,6]])

In [6]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
C = np.matrix('1,2;4,4')

In [8]:
C

matrix([[1, 2],
        [4, 4]])