In [1]:
import numpy as np

In [2]:
A = np.matrix('1,2,3;4,5,6;7,8,9')

In [3]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
A.shape

(3, 3)

In [5]:
#slicing
A[:]

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Não pode esquecer da indexação do python - começa em zero

In [7]:
A[2,1]

8

In [8]:
A [1,:]

matrix([[4, 5, 6]])

In [9]:
A[:,0]

matrix([[1],
        [4],
        [7]])

In [10]:
B = A

In [11]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
B[1,2] = 77

In [13]:
B

matrix([[ 1,  2,  3],
        [ 4,  5, 77],
        [ 7,  8,  9]])

In [14]:
A

matrix([[ 1,  2,  3],
        [ 4,  5, 77],
        [ 7,  8,  9]])

In [15]:
#Cópia de Matrizes
C = B.copy()

In [16]:
C

matrix([[ 1,  2,  3],
        [ 4,  5, 77],
        [ 7,  8,  9]])

In [17]:
C[2,2]= 14

In [18]:
C

matrix([[ 1,  2,  3],
        [ 4,  5, 77],
        [ 7,  8, 14]])

In [19]:
B

matrix([[ 1,  2,  3],
        [ 4,  5, 77],
        [ 7,  8,  9]])