In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4])

In [3]:
v

array([1, 2, 3, 4])

In [4]:
type(v)

numpy.ndarray

In [5]:
lista = [22, 5, 21, 7]

In [6]:
v1 = np.array(lista)

In [7]:
v1

array([22,  5, 21,  7])

##Representação vetorial (Base canônica)


In [8]:
e1 = np.array((1, 0, 0))
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

In [9]:
e1

array([1, 0, 0])